source/WebAppAgendamentoDeServicos/AgendMovies/AgendMovies/Controllers/SessoesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgendMovies.Modelos;

namespace AgendMovies.Controllers
{
    public class SessoesController : Controller
    {
        //Tabelas context = new Tabelas();
        //// GET: Sessoes
        //public ActionResult Listar()
        //{
           
        //    if (context.Sessoes.Count() <= 0)
        //    {
        //        List<string> Dias = new List<string> { "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab" }; 
        //        for (int i = 0; i < 7; i++)
        //        {
        //            context.Sessoes.Add(new Sessao() { diaSemana = Dias [i] });
        //        }
        //    }
        //    context.SaveChanges();
        //    return View(context.Sessoes.OrderBy(s => s.SessaoId));
        //}

        //public ActionResult Editar(long? id)
        //{
        //    ViewBag.Sessoes = context.Sessoes.OrderBy(p => p.SessaoId).ToList();
        //    return View(context.Sessoes.Find(id));
        //}

       
        //[HttpPost]
        //public ActionResult Editar(Sessao s)
        //{
        //    if (ModelState.IsValid)
        //    {
               
        //        context.Entry(s).State = EntityState.Modified;
        //        context.SaveChanges();
        //        return RedirectToAction("Listar");
        //    }
        //    return RedirectToAction("Listar");
        //}
        //public ActionResult Selecionar(long? id)
        //{
        //    Sessao p = context.Sessoes.Find(id);
        //    Session["Sessao"] = p;
        //    return RedirectToAction("Listar");
        //}
        //public ActionResult Limpar()
        //{

        //    Sessao x = (Sessao)Session["Sessao"];

        //    if (x != null)
        //    {
        //        Sessao p = new Sessao();
        //        p.SessaoId = x.SessaoId;
        //        p.diaSemana = x.diaSemana;
        //        context.Entry(p).State = EntityState.Modified;
        //        context.SaveChanges();
        //    }

        //    return RedirectToAction("Listar");
        //}
    }
}

source/WebAppAgendamentoDeServicos/AgendMovies/AgendMovies/Views/Sessoes/Editar.cshtml
@model AgendMovies.Modelos.Sessao


@{
    Layout = null;
    var sess = ViewBag.Sessoes as IEnumerable<AgendMovies.Modelos.Sessao>;
}

@*
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Add_Exc_sessão</title>
        <link href="@Url.Content("~/styles/adicionar_excluir_sessao.css")" rel="stylesheet" type="text/css" />
        <link rel="icon" href="~/img/icon.svg" />
    </head>
    <body>

        <header>
            <div id="Header_Organizador">
                <div>
                    <a href="index.html"><p><img src="~/img/Logo.png"></p></a>
                </div>
                <div>
                    <a href="login.html"><p><img src="~/img/logout_branco.png"></p></a>
                </div>
            </div>
        </header>
        <div><h1 id="LdS">Lista de Filmes</h1></div>

        <div id="ordem">
            <section>
                @foreach (var item in sess)
                {
                    <div id="vertical">
                        <div id="dia_da_semana">
                            <p id="D">@item.diaSemana</p>
                            @item.data
                        </div>

                        <div id="Manha">
                            <p>Manhã</p>
                            <ol>
                                <li>@item.manhaInicio</li>
                                <li>@item.manhaFim</li>
                            </ol>
                        </div>

                        <div id="Tarde">
                            <p>Tarde</p>
                            <ol>
                                <li>@item.tardeInicio</li>
                                <li>@item.tardeFim</li>
                            </ol>
                        </div>

                        <div id="Noite">
                            <p>Noite</p>
                            <ol>
                                <li>@item.noiteInicio</li>
                                <li>@item.noiteFim</li>
                            </ol>
                        </div>

                        <div id="LegDub">
                            <ol>
                                @if (item.leg == true)
                                {
                                    <li><p id="p">Leg</p></li>
                                }
                                @if (item.dub == true)
                                {
                                    <li><p id="p">Dub</p></li>
                                }


                            </ol>
                        </div>


                    </div>


                }

                <div id="b" style="margin: 0 auto; margin-bottom: 1em;">
                    <button>
                        <a href="@Url.Action("Limpar", "Sessoes")" style="width: 100%; height: 100%; color: White; text-decoration: none; ">Limpar </a>
                    </button>
                </div>
        </div>
        </section>
        <section style="margin: 0 auto;">
            @using (Html.BeginForm())
            {
                <div id="vertical">
                    <div id="dia_da_semana">
                        <p id="D">@Model.diaSemana</p>

                        @Html.TextBoxFor(model => model.data, new { type = "date", required = "required", id = "date" })
                    </div>

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.SessaoId)
                    @Html.HiddenFor(model => model.diaSemana)

                    <div id="Manha">
                        <p>Manhã</p>
                        <ol>


                            <li>@Html.TextBoxFor(model => model.manhaInicio, new { type = "time", required = "required", id = "appt" })</li>
                            <li>@Html.TextBoxFor(model => model.manhaFim, new { type = "time", required = "required", id = "appt" })</li>
                        </ol>
                    </div>

                    <div id="Tarde">
                        <p>Tarde</p>
                        <ol>
                            <li>@Html.TextBoxFor(model => model.tardeInicio, new { type = "time", required = "required", id = "appt" })</li>
                            <li>@Html.TextBoxFor(model => model.tardeFim, new { type = "time", required = "required", id = "appt" })</li>
                        </ol>
                    </div>

                    <div id="Noite">
                        <p>Noite</p>
                        <ol>
                            <li>@Html.TextBoxFor(model => model.noiteInicio, new { type = "time", required = "required", id = "appt" })</li>
                            <li>@Html.TextBoxFor(model => model.noiteFim, new { type = "time", required = "required", id = "appt" })</li>
                        </ol>
                    </div>

                    <div id="LegDub">
                        <ol>
                            <li><p id="p">Leg</p>  @Html.EditorFor(model => model.leg)</li>
                            <li><p id="p">Dub</p>  @Html.EditorFor(model => model.dub)</li>
                        </ol>
                    </div>

                    <div id="b" style="margin: 0 auto; margin-bottom: 1em;">
                        <button>
                            <input type="submit" value="Editar" style="background-color: transparent; color: white; border: none;"/>
                        </button>

                    </div>



                </div>
            }
        </section>
        </div>

        <footer>

            <div>
                <p>Copyright © 2023 AgendMovies</p>
            </div>
            <div>
                <ol>
                    <a href="#.html">
                    <li><img src="img/insta.png"></li></a>
                    <a href="#.html">
                    <li><img src="img/face.png"></li></a>
                    <a href="#.html">
                    <li><img src="img/X.png"></li></a>
                </ol>
            </div>
        </footer>




    </body>
    </html>*@

source/WebAppAgendamentoDeServicos/AgendMovies/AgendMovies/Views/Sessoes/Listar.cshtml
@model IEnumerable<AgendMovies.Modelos.Sessao>

@{
    Layout = null;
}


@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add_Exc_sessão</title>
    <link href="@Url.Content("~/styles/adicionar_excluir_sessao.css")" rel="stylesheet" type="text/css" />
    <link rel="icon" href="~/img/icon.svg" />
</head>
<body>

    <header>
        <div id="Header_Organizador">
            <div>
                <a href="index.html"><p><img src="~/img/Logo.png"></p></a>
            </div>
            <div>
                <a href="login.html"><p><img src="~/img/logout_branco.png"></p></a>
            </div>
        </div>
    </header>
    <div><h1 id="LdS">Lista de Filmes</h1></div>

    <div id="ordem">
        <section>
            @foreach (var item in Model)
            {
                <div id="vertical">
                    <div id="dia_da_semana">
                        <p id="D"><a href="@Url.Action("Selecionar", "Sessoes", new { id = item.SessaoId })" style="color: red; text-decoration: none;">@item.diaSemana</a></p>
                        @item.data
                    </div>

                    <div id="Manha">
                        <p>Manhã</p>
                        <ol>
                            <li>@item.manhaInicio</li>
                            <li>@item.manhaFim</li>
                        </ol>
                    </div>

                    <div id="Tarde">
                        <p>Tarde</p>
                        <ol>
                            <li>@item.tardeInicio</li>
                            <li>@item.tardeFim</li>
                        </ol>
                    </div>

                    <div id="Noite">
                        <p>Noite</p>
                        <ol>
                            <li>@item.noiteInicio</li>
                            <li>@item.noiteFim</li>
                        </ol>
                    </div>

                    <div id="LegDub">
                        <ol>
                            @if (item.leg == true)
                            {
                                <li><p id="p">Leg</p></li>
                            }
                            @if (item.dub == true)
                            {
                                <li><p id="p">Dub</p></li>
                            }


                        </ol>
                    </div>

                    <div id="b">
                        <button>
                            <a href="@Url.Action("Editar", "Sessoes", new { id = item.SessaoId })" style="width: 100%; height: 100%; color: white; text-decoration: none;">Editar </a>
                        </button>
                    </div>
                </div>


            }

            <div  id="b" style="margin: 0 auto; margin-bottom: 1em;">
                <button >
                    <a  href="@Url.Action("Limpar", "Sessoes")" style="width: 100%; height: 100%; color: White; text-decoration: none; ">Limpar </a>
                </button>
            </div>
    </div>
    </section>
    </div>

    <footer>

        <div>
            <p>Copyright © 2023 AgendMovies</p>
        </div>
        <div>
            <ol>
                <a href="#.html">
                <li><img src="img/insta.png"></li></a>
                <a href="#.html">
                <li><img src="img/face.png"></li></a>
                <a href="#.html">
                <li><img src="img/X.png"></li></a>
            </ol>
        </div>
    </footer>




</body>
</html>*@