source/Antigos/AgendMovies/AgendMovies/Controllers/AdmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgendMovies.Controllers
{
    public class AdmController : Controller
    {
        // GET: Adm
        public ActionResult AdmPage()
        {
            return View();
        }
    }
}

source/Antigos/AgendMovies/AgendMovies/Controllers/CRUDFilmesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgendMovies.Modelos;

namespace AgendMovies.Controllers
{
    public class CRUDFilmesController : Controller
    {
        Tabelas context = new Tabelas();
        // GET: CRUDFilmes
        public ActionResult Listar()
        {
            return View(context.Filmes.OrderByDescending(f => f.FilmeId));
        }
        public ActionResult Adicionar()
        {
            return View();
        }
        public ActionResult Editar(long? id)
        {
            try
            {
                Filme x = (Filme)Session["Filme"];
                id = x.FilmeId;
                return View(context.Filmes.Find(id));
            }
            catch
            {
                return RedirectToAction("Listar");
            }
           
        }
        public ActionResult Visualizar(long? id)
        {
            try
            {
                Filme x = (Filme)Session["Filme"];
                id = x.FilmeId;
                return View(context.Filmes.Find(id));
            }
            catch
            {
                return RedirectToAction("Listar");
            }

        }

        [HttpPost]
        public ActionResult Editar(Filme f, HttpPostedFileBase arquivo)
        {

            if (ModelState.IsValid)
            {
                if (arquivo != null)
                {
                    f.TipoDaFoto = arquivo.ContentType;
                    f.ConteudoDaFoto = SetLogoTipo(arquivo);

                }
                context.Entry(f).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Listar");
            }
            return RedirectToAction("Listar");


        }
        [HttpPost]
        public ActionResult Adicionar(Filme f, HttpPostedFileBase arquivo)
        {
            
            try
            {
                if (arquivo != null)
                {
                    f.TipoDaFoto = arquivo.ContentType;
                    f.ConteudoDaFoto = SetLogoTipo(arquivo);

                }
                context.Filmes.Add(f);
                context.SaveChanges();
                return RedirectToAction("Listar");
            }
            catch
            {
                return RedirectToAction("Listar");
            }
            
        }

        public ActionResult Selecionar(long? id)
        {
            Filme p = context.Filmes.Find(id);
            Session["Filme"] = p;
            TempData["Id"] = id;
            return RedirectToAction("Listar");
        }

        public ActionResult Delete()
        {

            Filme x = (Filme)Session["Filme"];

            if (x != null)
            {
                Filme p = context.Filmes.Find(x.FilmeId);
                context.Filmes.Remove(p);
                context.SaveChanges();
            }

            return RedirectToAction("Listar");
        }

        private byte[] SetLogoTipo(HttpPostedFileBase arquivo)
        {
            var bytesFile = new byte[arquivo.ContentLength];
            arquivo.InputStream.Read(bytesFile, 0, arquivo.ContentLength);
            return bytesFile;
        }
        public FileContentResult GetLogoTipo(int? id)
        {

            Filme F = context.Filmes.Find(id);
            if (F != null)
            {
                return File(F.ConteudoDaFoto, F.TipoDaFoto);
            }
            return null;
        }
    }
}

source/Antigos/AgendMovies/AgendMovies/Views/CRUDFilmes/Adicionar.cshtml
@model AgendMovies.Modelos.Filme

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-height, initial-scale=1.0">
    <title>Agend Movies</title>
    <link rel="stylesheet" href="~/styles/CriarFilmesADM.css" />
    <link rel="icon" href="~/img/icon.svg" />
    <style>
        .Esconde{
            display: none;
        }
    </style>
    <script>function AtualizarImg(doc, input){
        var Img = document.getElementById(doc);
        var Inp = document.getElementById(input);

        Inp.addEventListener("change", function (evento) {


            const Arquivo = evento.target.files[0];
            if (Arquivo) {
                const LeitorDeArquivo = new FileReader();
                LeitorDeArquivo.onload = function (e) {
                    Img.setAttribute('src', e.target.result);
                };
                LeitorDeArquivo.readAsDataURL(Arquivo);
            }
        });
        Inp.click();
      }</script>
</head>
<body>
    <header>
        <figure>
            <a href="index.html"><img src="~/img/logoSite.png" alt="Logo do site" /></a>
        </figure>

        <figure>
            <a href="#"><img src="~/img/logout_branco.png" alt="Icone de logout" /></a>
        </figure>
    </header>
    <main>
        <section>
            <figure onclick="AtualizarImg('CapaFilme', 'InputImg')">
                <img id="CapaFilme" src="~/img/CapaIndefinida.png" alt="Capa do filme" />
            </figure>
            <div>
                <h2>Cadastro de Filme</h2>
                @using (Html.BeginForm("Adicionar", "CRUDFilmes", FormMethod.Post,
new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "")

                    @Html.HiddenFor(model => model.FilmeId)
                    @Html.TextBox("arquivo", "", new { type = "file", id = "InputImg", @class = "Esconde"})

             
                    <div>
                        <label for="NomeFilme">Nome do filme:</label>
                         @Html.TextBoxFor(model => model.Nome, new { type = "text", required = "required", id = "NomeFilme" })
                    </div>
                    <div>
                        
                        @{

                            var gens = new List<SelectListItem>
                            {
                                new SelectListItem { Value = "Ação", Text = "Ação" },
                                new SelectListItem { Value = "Comedia", Text = "Comedia" },
                                new SelectListItem { Value = "Terror", Text = "Terror" },
                                new SelectListItem { Value = "Aventura", Text = "Aventura" },
                                new SelectListItem { Value = "Romance", Text = "Romance" },
                                new SelectListItem { Value = "Drama", Text = "Drama" }
                            };
                        }
                        <label for="Genero">Genero:</label>
                        @Html.DropDownListFor(model => model.Genero, gens, new { required = "required", id = "Genero" })
                    </div>
                    <div>
                        
                        @{

                            var ind = new List<SelectListItem>
                                        {
                                new SelectListItem { Value = "Livre", Text = "Livre" },
                                new SelectListItem { Value = "10", Text = "10" },
                                new SelectListItem { Value = "12", Text = "12" },
                                new SelectListItem { Value = "14", Text = "14" },
                                new SelectListItem { Value = "16", Text = "16" },
                                new SelectListItem { Value = "18", Text = "18" }
                            };
                        }
                        <label for="Indicativa">Classificação indicativa:</label>
                        @Html.DropDownListFor(model => model.Indicativa, ind, new { required = "required", id = "Indicativa" })
                    </div>
                    <div>
                        <label for="Sinopse">Sinopse:</label>
                        @Html.TextAreaFor(model => model.Sinopse, new { maxlength = 820, id = "Sinopse" })
                    </div>
                    <input class="Adicionar" type="submit" value="Adicionar" />
             
                }
            </div>

        </section>
    </main>
    <footer>
        <p>Copyright © 2023 AgendMovies</p>
        <ol>
            <li><a href="#"><img src="~/img/insta.png" alt="Logo do Instagram" /></a></li>
            <li><a href="#"><img src="~/img/face.png" alt="Logo do Facebook" /></a></li>
            <li><a href="#"><img src="~/img/X.png" alt="Logo do Twitter" /></a></li>
        </ol>
    </footer>
</body>
</html>

source/Antigos/AgendMovies/AgendMovies/Views/CRUDFilmes/Editar.cshtml
@model AgendMovies.Modelos.Filme

@{
    Layout = null;
}

!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-height, initial-scale=1.0">
    <title>Agend Movies</title>
    <link rel="stylesheet" href="~/styles/CriarFilmesADM.css" />
    <link rel="icon" href="~/img/icon.svg" />
    <style>
        .Esconde {
            display: none;
        }
    </style>
    <script>
function AtualizarImg(doc, input){
        var Img = document.getElementById(doc);
        var Inp = document.getElementById(input);

        Inp.addEventListener("change", function (evento) {


            const Arquivo = evento.target.files[0];
            if (Arquivo) {
                const LeitorDeArquivo = new FileReader();
                LeitorDeArquivo.onload = function (e) {
                    Img.setAttribute('src', e.target.result);
                };
                LeitorDeArquivo.readAsDataURL(Arquivo);
            }
        });
        Inp.click();
      }</script>
</head>
<body>
    <header>
        <figure>
            <a href="index.html"><img src="~/img/logoSite.png" alt="Logo do site" /></a>
        </figure>

        <figure>
            <a href="#"><img src="~/img/logout_branco.png" alt="Icone de logout" /></a>
        </figure>
    </header>
    <main>
        <section>
            <figure onclick="AtualizarImg('CapaFilme', 'InputImg')">
                @if (Model.ConteudoDaFoto == null)
                {
                    <img id="CapaFilme" src="~/img/CapaIndefinida.png" alt="Capa do filme" />
                }
                else
                {
                    <img id="CapaFilme" src="@Url.Action("GetLogoTipo", "CRUDFilmes", new {id = Model.FilmeId})" alt="Capa do filme" />
                }
            </figure>
            <div>
                <h2>Cadastro de Filme</h2>
                @using (Html.BeginForm("Editar", "CRUDFilmes", FormMethod.Post,
new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "")

                    @Html.HiddenFor(model => model.FilmeId)
                    @Html.HiddenFor(model => model.ConteudoDaFoto)
                    @Html.HiddenFor(model => model.TipoDaFoto)
        
                    @Html.TextBox("arquivo", "", new { type = "file", id = "InputImg", @class = "Esconde" })


                    <div>
                        <label for="NomeFilme">Nome do filme:</label>
                        @Html.TextBoxFor(model => model.Nome, new { type = "text", required = "required", id = "NomeFilme" })
                    </div>
                    <div>

                        @{

                            var gens = new List<SelectListItem>
                                                                {
                                new SelectListItem { Value = "Ação", Text = "Ação" },
                                new SelectListItem { Value = "Comedia", Text = "Comedia" },
                                new SelectListItem { Value = "Terror", Text = "Terror" },
                                new SelectListItem { Value = "Aventura", Text = "Aventura" },
                                new SelectListItem { Value = "Romance", Text = "Romance" },
                                new SelectListItem { Value = "Drama", Text = "Drama" }
                            };
                        }
                        <label for="Genero">Genero:</label>
                        @Html.DropDownListFor(model => model.Genero, gens, new { required = "required", id = "Genero" })
                    </div>
                    <div>

                        @{

                            var ind = new List<SelectListItem>
                                                                            {
                                new SelectListItem { Value = "Livre", Text = "Livre" },
                                new SelectListItem { Value = "10", Text = "10" },
                                new SelectListItem { Value = "12", Text = "12" },
                                new SelectListItem { Value = "14", Text = "14" },
                                new SelectListItem { Value = "16", Text = "16" },
                                new SelectListItem { Value = "18", Text = "18" }
                            };
                        }
                        <label for="Indicativa">Classificação indicativa:</label>
                        @Html.DropDownListFor(model => model.Indicativa, ind, new { required = "required", id = "Indicativa" })
                    </div>
                    <div>
                        <label for="Sinopse">Sinopse:</label>
                        @Html.TextAreaFor(model => model.Sinopse, new { maxlength = 820, id = "Sinopse" })
                    </div>
                    <input class="Adicionar" type="submit" value="Editar" />

                }
            </div>

        </section>
    </main>
    <footer>
        <p>Copyright © 2023 AgendMovies</p>
        <ol>
            <li><a href="#"><img src="~/img/insta.png" alt="Logo do Instagram" /></a></li>
            <li><a href="#"><img src="~/img/face.png" alt="Logo do Facebook" /></a></li>
            <li><a href="#"><img src="~/img/X.png" alt="Logo do Twitter" /></a></li>
        </ol>
    </footer>
</body>
</html>

source/Antigos/AgendMovies/AgendMovies/Views/CRUDFilmes/Listar.cshtml
@model IEnumerable<AgendMovies.Modelos.Filme>

@{
    var idSele = TempData["Id"];
}


<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-height, initial-scale=1.0">
    <title>Agend Movies</title>
    <link rel="stylesheet" href="~/styles/FilmeAdm.css" />
    <link rel="icon" href="~/img/icon.svg" />
</head>
<body>
    <header>
        <figure>
            <a href="@Url.Action("AdmPage", "Adm")"><img src="~/img/logoSite.png" alt="Logo do site" /></a>
        </figure>

        <figure>
            <a href="#"><img src="~/img/logout_branco.png" alt="Icone de logout" /></a>
        </figure>
    </header>
    <main>
        <section>
            <h2>Filmes</h2>
            <div class="Conteudo">
                <ol>
                    @foreach (var Filme in Model)
                    {
                        if (idSele != null)
                        {
                            if (long.Parse(idSele.ToString()) == Filme.FilmeId)
                            {
                                <li><a  style="background-color: #a1a1a1 !important;" href="@Url.Action("Selecionar", "CRUDFilmes", new { id = Filme.FilmeId })">@Filme.Nome</a></li>
                            }
                            else
                            {
                                <li ><a  href="@Url.Action("Selecionar", "CRUDFilmes", new { id = Filme.FilmeId })">@Filme.Nome</a></li>
                            }
                        }
                        else
                        {
                            <li><a href="@Url.Action("Selecionar", "CRUDFilmes", new { id = Filme.FilmeId })">@Filme.Nome</a></li>
                        }

                    }

                </ol>
                <div>
                    <ol>
                        <li><a class="Excluir" href="@Url.Action("Delete", "CRUDFilmes")">Excluir</a></li>
                        <li><a class="Adicionar" href="@Url.Action("Adicionar", "CRUDFilmes")">Adicionar</a></li>
                        <li><a class="Adicionar" href="@Url.Action("Editar", "CRUDFilmes")">Editar</a></li>
                        <li><a class="Adicionar" href="@Url.Action("Visualizar", "CRUDFilmes")">Visualizar</a></li>
                    </ol>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <p>Copyright © 2023 AgendMovies</p>
        <ol>
            <li><a href="#"><img src="~/img/insta.png" alt="Logo do Instagram" /></a></li>
            <li><a href="#"><img src="~/img/face.png" alt="Logo do Facebook" /></a></li>
            <li><a href="#"><img src="~/img/X.png" alt="Logo do Twitter" /></a></li>
        </ol>
    </footer>
</body>
</html>

source/Antigos/AgendMovies/AgendMovies/Views/CRUDFilmes/Visualizar.cshtml
@model AgendMovies.Modelos.Filme

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Visualizar</title>
</head>
<body>
    <div>
        <h4>Filme</h4>
        @if (Model.ConteudoDaFoto == null)
        {
            <img id="CapaFilme" src="~/img/CapaIndefinida.png" alt="Capa do filme" />
        }
        else
        {
            <img id="CapaFilme" src="@Url.Action("GetLogoTipo", "CRUDFilmes", new {id = Model.FilmeId})" alt="Capa do filme" />
        }
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sinopse)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sinopse)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Indicativa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Indicativa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Genero)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Genero)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConteudoDaFoto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConteudoDaFoto)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TipoDaFoto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TipoDaFoto)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.FilmeId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>