source/AgendMovies/AgendMovies/Controllers/EmployeesController.cs
using AgendMovies.Modelos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;

namespace AgendMovies.Controllers
{
    public class EmployeesController : Controller
    {
        // GET: Employees
        Tabelas Banco = new Tabelas();

        public ActionResult Home()
        {
            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                return View(f);
            }
            return RedirectToAction("Login");
           
        }
     
        public ActionResult Cadastrar()
        {
            return View(new Funcionario());
        }
        public ActionResult Listar()
        {

            return View(Banco.Funcionarios.OrderBy(f => f.FuncionarioId));
        }
        public ActionResult VerPacotesComprados()
        {


           

            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                List<Compra> Compras = Banco.Compras.OrderByDescending(c => c.CompraId).ToList();
                List<VerPerfilView> ComprasView = new List<VerPerfilView>();
                foreach (Compra C in Compras)
                {
                    VerPerfilView mc = new VerPerfilView();
                    mc.Compra = C;
                    mc.Sessao = Banco.Sessoes.Find(C.IdSessao);
                    mc.Filme = Banco.Filmes.Find(mc.Sessao.IdFilme);
                    mc.Pacote = Banco.Pacotes.Find(C.IdPacote);
                    mc.Cliente = Banco.Clientes.Find(C.IdCliente);
                    ComprasView.Add(mc);
                }
                return View(ComprasView);
            }
            return RedirectToAction("Login");

        }
        public ActionResult ExlcluirPacoteComprado(long id)
        {

            Compra Compra = Banco.Compras.Find(id);
            Banco.Compras.Remove(Compra);
            Banco.SaveChanges();

            return RedirectToAction("VerPacotesComprados");

        }
        public ActionResult Login()
        {

            return View(new Funcionario());

        }
        [HttpPost]
        public ActionResult Login(Funcionario f)
        {

            Funcionario fun = Banco.Funcionarios.FirstOrDefault(c => c.email == f.email && c.senha == f.senha);
            if (fun != null)
            {
                Session["Funcionario"] = fun;
                return RedirectToAction("Home");
            }
            if(f.email.ToLower() == "adm@adm" && f.senha == "adm")
            {
                return RedirectToAction("Home", "Adm");
            }
            return RedirectToAction("Login");

        }
        public ActionResult VerPacoteComprado(long id)
        {

            
            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                Compra Compra = Banco.Compras.Find(id);

                VerPerfilView mc = new VerPerfilView();
                mc.Compra = Compra;
                mc.Sessao = Banco.Sessoes.Find(Compra.IdSessao);
                mc.Filme = Banco.Filmes.Find(mc.Sessao.IdFilme);
                mc.Pacote = Banco.Pacotes.Find(Compra.IdPacote);
                mc.Cliente = Banco.Clientes.Find(Compra.IdCliente);

                return View(mc);
            }
            return RedirectToAction("Login");

        }
        public ActionResult Editar(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f == null)
            {
                return RedirectToAction("Listar");
            }
            return View(f);
        }
        public ActionResult Excluir(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f != null)
            {
                Banco.Funcionarios.Remove(f);
                Banco.SaveChanges();
            }
            return RedirectToAction("Listar");
        }
        public ActionResult Ver(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f != null)
            {
                return View(f);
            }
            return RedirectToAction("Listar");
        }
        [HttpPost]
        public ActionResult Editar(Funcionario f, HttpPostedFileBase arquivo)
        {
            if (ModelState.IsValid)
            {
                if (arquivo != null)
                {
                    f.TipoDaFoto = arquivo.ContentType;
                    f.Foto = SetLogoTipo(arquivo);

                }
                Banco.Entry(f).State = EntityState.Modified;
                Banco.SaveChanges();
                return RedirectToAction("Listar");
            }
            return RedirectToAction("Listar");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Funcionario f, HttpPostedFileBase arquivo)
        {

            if (arquivo != null)
            {
                f.TipoDaFoto = arquivo.ContentType;
                f.Foto = SetLogoTipo(arquivo);
            }
            Banco.Funcionarios.Add(f);
            Banco.SaveChanges();
            //return RedirectToAction("Visualizar", "Funcionarios");
            return RedirectToAction("Listar");

        }



        private byte[] SetLogoTipo(HttpPostedFileBase arquivo)
        {
            var bytesFile = new byte[arquivo.ContentLength];
            arquivo.InputStream.Read(bytesFile, 0, arquivo.ContentLength);
            return bytesFile;
        }
        public FileContentResult GetLogoTipo(int? id)
        {

            Funcionario F = Banco.Funcionarios.Find(id);
            if (F != null)
            {
                return File(F.Foto, F.TipoDaFoto);
            }
            return null;
        }

    }
}

source/AgendMovies/AgendMovies/Controllers/PacotesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgendMovies.Modelos;

namespace AgendMovies.Controllers
{
    public class PacotesController : Controller
    {

        // GET: Pacotes
        Tabelas T = new Tabelas();

        public ActionResult Visualizar()
        {
            
            

            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                return View(T.Pacotes.OrderBy(pacotes => pacotes.PacotesId));
            }
            return RedirectToAction("Login");
        }
        public ActionResult Cadastrar()
        {
            


            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                ViewBag.Quant = T.Pacotes.OrderBy(pacotes => pacotes.nome).ToList().Count();
                ViewBag.Pacotes = T.Pacotes.OrderBy(pacotes => pacotes.nome);

                return View();
            }
            return RedirectToAction("Login");
        }
        public ActionResult Editar(long? id)
        {
           


            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                if (id == null)
                {
                    return HttpNotFound();
                }

                Pacotes pacote = T.Pacotes.Find(id);

                if (pacote == null)
                {
                    return HttpNotFound();
                }

                return View(pacote);
            }
            return RedirectToAction("Login");
        }
        public ActionResult VerPacote(long? id)
        {
          


            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                if (id == null)
                {
                    return HttpNotFound();
                }

                Pacotes pacote = T.Pacotes.Find(id);

                if (pacote == null)
                {
                    return HttpNotFound();
                }

                return View(pacote);
            }
            return RedirectToAction("Login");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Pacotes pacote)
        {
            if (ModelState.IsValid)
            {
                // Assuming that Pacotes has a property named PacotesId as the primary key
                T.Entry(pacote).State = EntityState.Modified; // EntityState.Modified is from System.Data.Entity
                T.SaveChanges();
                return RedirectToAction("Visualizar");
            }

            ViewBag.Quant = T.Pacotes.OrderBy(p => p.nome).ToList().Count();
            return View(pacote);
        }
        [HttpPost]
        public ActionResult Cadastrar(Pacotes p)
        {
            if (T.Pacotes.OrderBy(x => x.nome).Count() < 6)
            {
                T.Pacotes.Add(p);
                T.SaveChanges();
                return RedirectToAction("Visualizar");
            }
            return RedirectToAction("Visualizar");
        }
     
        public ActionResult Excluir(long id)
        {    
            Pacotes p = T.Pacotes.Find(id);
            T.Pacotes.Remove(p);
            T.SaveChanges();

            List<Compra> compras = T.Compras.OrderBy(c => c.CompraId).Where(comp => comp.IdPacote == id).ToList();
            foreach (Compra c in compras)
            {
                T.Compras.Remove(c);
                T.SaveChanges();
            }

            return RedirectToAction("Visualizar");
        }
        

    }
}

source/AgendMovies/AgendMovies/Views/Pacotes/Cadastrar.cshtml
@model AgendMovies.Modelos.Pacotes

@{
    Layout = null;
    var funcionario = ViewBag.Funcionario as AgendMovies.Modelos.Funcionario;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link href="~/styles/EditarPacote.css" rel="stylesheet" />
    <link rel="icon" href="~/img/Logo_aba.png" />
    <script src="beattlejuice.js"></script>
    <style>
        form button {
            cursor: pointer;
        }

      

        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        header > div > p {
            color: black !important;
        }
    </style>
</head>
<body>
    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Employees")">Home</a></li>
            <li><a href="@Url.Action("Visualizar", "Pacotes")">Pacotes</a></li>
            <li><a href="@Url.Action("VerPacotesComprados", "Employees")">Pacotes comprados</a></li>
            <li><a href="#">Sobre Nós</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>
                    @if (funcionario.Foto == null)
                    {
                        <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">
                    }
                    else
                    {
                        <img class="FotoPerfilHeader" src="@Url.Action("GetLogoTipo", "Employees", new {id = funcionario.FuncionarioId})">
                    }

                </p>
            </a>
            <p id="per">@funcionario.nome</p>
        </div>
    </header>
    <!-- 246 -->
    <main>
        <section>


            <div id="organ"><h1>Cadastrar pacote </h1></div>


            @using (Html.BeginForm("Cadastrar", "Pacotes", FormMethod.Post,
new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <ol>
                    <li id="li1">
                        <p>Nome:</p>

                        @Html.TextBoxFor(model => model.nome, new { type = "text", required = "required" })
                    </li>
                    <li id="li2">
                        <p>Ingressos:</p>

                        @Html.TextBoxFor(model => model.ingressos, new { type = "number", required = "required" })
                    </li>
                    <li id="li3">
                        <p>Valor:</p>

                        @Html.TextBoxFor(model => model.valor, new { type = "number", required = "required" })
                    </li>
                    <div id="b">
                        <button type="submit">Salvar</button>
                    </div>
                </ol>

                <!--<div id="b">
                <button>Cadastrar</button>
                </div>-->}


        </section>
    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>
</body>
</html>

source/AgendMovies/AgendMovies/Views/Pacotes/Editar.cshtml
@model AgendMovies.Modelos.Pacotes

@{
    Layout = null;
    var funcionario = ViewBag.Funcionario as AgendMovies.Modelos.Funcionario;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link href="~/styles/EditarPacote.css" rel="stylesheet" />
    <link rel="icon" href="~/img/Logo_aba.png" />
    <script src="beattlejuice.js"></script>
    <style>
        form button {
            cursor: pointer;
        }

     
        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        header > div > p {
            color: black !important;
        }
 
    </style>
</head>
<body>
    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Employees")">Home</a></li>
            <li><a href="@Url.Action("Visualizar", "Pacotes")">Pacotes</a></li>
            <li><a href="@Url.Action("VerPacotesComprados", "Employees")">Pacotes comprados</a></li>
            <li><a href="#">Sobre Nós</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>
                    @if (funcionario.Foto == null)
                    {
                        <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">
                    }
                    else
                    {
                        <img class="FotoPerfilHeader" src="@Url.Action("GetLogoTipo", "Employees", new {id = funcionario.FuncionarioId})">
                    }

                </p>
            </a>
            <p id="per">@funcionario.nome</p>
        </div>
    </header>
    <!-- 246 -->
    <main>
        <section>


            <div id="organ"><img id="olho" src="~/img/pen.png"><h1>Editar pacote </h1></div>

      
                @using (Html.BeginForm("Editar", "Pacotes", FormMethod.Post,
new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.PacotesId)
                    <ol>
                        <li id="li1">
                            <p>Nome:</p>
                 
                            @Html.TextBoxFor(model => model.nome, new { type = "text", required = "required" })
                        </li>
                        <li id="li2">
                            <p>Ingressos:</p>
                        
                            @Html.TextBoxFor(model => model.ingressos, new { type = "number", required = "required" })
                        </li>
                        <li id="li3">
                            <p>Valor:</p>
                   
                            @Html.TextBoxFor(model => model.valor, new { type = "number", required = "required" })
                        </li>
                        <div id="b">
                            <button type="submit">Salvar</button>
                        </div>
                    </ol>

                    <!--<div id="b">
        <button>Cadastrar</button>
        </div>-->}
        

        </section>
    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>
</body>
</html>

source/AgendMovies/AgendMovies/Views/Pacotes/VerPacote.cshtml
@model AgendMovies.Modelos.Pacotes

@{
    Layout = null;
    var funcionario = ViewBag.Funcionario as AgendMovies.Modelos.Funcionario;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link href="~/styles/VerPacote.css" rel="stylesheet" />
    <link rel="icon" href="~/img/Logo_aba.png" />
    <script src="beattlejuice.js"></script>
    <style>


        .BordaBaixa {
            border-bottom: 1px solid white;
            width: 100%;
        }

     
        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        header > div > p {
            color: black !important;
        }
 
    </style>
</head>
<body>
    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Employees")">Home</a></li>
            <li><a href="@Url.Action("Visualizar", "Pacotes")">Pacotes</a></li>
            <li><a href="@Url.Action("VerPacotesComprados", "Employees")">Pacotes comprados</a></li>
            <li><a href="#">Sobre Nós</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>
                    @if (funcionario.Foto == null)
                    {
                        <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">
                    }
                    else
                    {
                        <img class="FotoPerfilHeader" src="@Url.Action("GetLogoTipo", "Employees", new {id = funcionario.FuncionarioId})">
                    }

                </p>
            </a>
            <p id="per">@funcionario.nome</p>
        </div>
    </header>
    <!-- 246 -->
    <main>
        <section>


            <div id="organ"><img id="olho" src="~/img/oljo.png"><h1>ver pacote</h1></div>

            <div id="borda">
                <ol>
                    <li id="li1"><p>Nome:</p><p class="BordaBaixa">@Model.nome</p></li>
                    <li id="li2"><p>Ingressos:</p><p class="BordaBaixa">@Model.ingressos</p></li>
                    <li id="li3"><p>Valor:</p><p class="BordaBaixa">@Model.valor</p></li>
                </ol>
                <!--<div id="b">
                <button>Cadastrar</button>
                </div>-->
            </div>

        </section>
    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>
</body>
</html>

source/AgendMovies/AgendMovies/Views/Pacotes/Visualizar.cshtml
@model IEnumerable<AgendMovies.Modelos.Pacotes>


@{
    Layout = null;
    var funcionario = ViewBag.Funcionario as AgendMovies.Modelos.Funcionario;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link href="~/styles/ListarPacotes.css" rel="stylesheet" />
    <link rel="icon" href="img/Logo_aba.png" />
    <script src="~/script/beattlejuice.js"></script>
    <script src="~/script/modal.js"></script>
    <link rel="stylesheet" href="~/styles/modalConfirm.css">
    <style>
        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        header > div > p {
            color: black !important;
        }
    </style>
</head>
<body>
    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Employees")">Home</a></li>
            <li><a href="@Url.Action("Visualizar", "Pacotes")">Pacotes</a></li>
            <li><a href="@Url.Action("VerPacotesComprados", "Employees")">Pacotes comprados</a></li>
            <li><a href="#">Sobre Nós</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>
                    @if (funcionario.Foto == null)
                    {
                        <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">
                    }
                    else
                    {
                        <img class="FotoPerfilHeader" src="@Url.Action("GetLogoTipo", "Employees", new {id = funcionario.FuncionarioId})">
                    }

                </p>
            </a>
            <p id="per">@funcionario.nome</p>
        </div>
    </header>
    <!-- 246 -->
    <main>
        <div id="uni">
            <h1 id="h11">PACOTES CADASTRADOS NO SISTEMA</h1>
        </div>

        <div id="org">
            <ol id="ol1">
                @foreach (var item in Model)
                {
                    <li>
                        <h1 id="pequena">@item.nome</h1><div>
                            <ol class="botoes">
                                <a href="@Url.Action("VerPacote", "Pacotes", new { id = item.PacotesId})">
                                <li><img src="~/img/oljo.png"></li>
                                <p>Ver </p></a>
                                <a href="@Url.Action("Editar", "Pacotes", new { id = item.PacotesId})"><li><img src="~/img/pen.png"></li><p>Editar</p></a>
                                 @{ 
                                    var IdModal = "ModalExclusao"+item.PacotesId.ToString() ;
                                }
                                <a href="javascript:AbrirModal('@IdModal')">
                                    <li>
                                        <img src="~/img/lixo.png">
                                    </li>
                                    <p>Excluir</p>
                               
                                   
                                </a>
                               
                                <div id="@IdModal" class="Modal">
                                    <div class="ModalConteudo">
                                        <h3>Atenção!</h3>
                                        <p>Tem certeza de que deseja excluir essa compra de @item.nome ? </p>
                                        <ol>
                                            <li><a href="@Url.Action("Excluir", "Pacotes", new { id = item.PacotesId})">Sim</a></li>
                                            <li><a href="javascript:FecharModal('@IdModal')">Não</a></li>
                                        </ol>
                                        <span class="TextoImg">Essa ação e irreversivel <img src="~/img/iconConfirmExclu.png" alt="Icone de alerta"/></span>
                                    </div>
                                </div>
                            </ol>
                        </div>
                    </li>
                }


            </ol>
        </div>



    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>
</body>
</html>