source/AgendMovies/AgendMovies/Controllers/EmployeesController.cs
using AgendMovies.Modelos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;

namespace AgendMovies.Controllers
{
    public class EmployeesController : Controller
    {
        // GET: Employees
        Tabelas Banco = new Tabelas();

        public ActionResult Home()
        {
            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                return View(f);
            }
            return RedirectToAction("Login");
           
        }
     
        public ActionResult Cadastrar()
        {
            return View(new Funcionario());
        }
        public ActionResult Listar()
        {

            return View(Banco.Funcionarios.OrderBy(f => f.FuncionarioId));
        }
        public ActionResult VerPacotesComprados()
        {


           

            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                List<Compra> Compras = Banco.Compras.OrderByDescending(c => c.CompraId).ToList();
                List<VerPerfilView> ComprasView = new List<VerPerfilView>();
                foreach (Compra C in Compras)
                {
                    VerPerfilView mc = new VerPerfilView();
                    mc.Compra = C;
                    mc.Sessao = Banco.Sessoes.Find(C.IdSessao);
                    mc.Filme = Banco.Filmes.Find(mc.Sessao.IdFilme);
                    mc.Pacote = Banco.Pacotes.Find(C.IdPacote);
                    mc.Cliente = Banco.Clientes.Find(C.IdCliente);
                    ComprasView.Add(mc);
                }
                return View(ComprasView);
            }
            return RedirectToAction("Login");

        }
        public ActionResult ExlcluirPacoteComprado(long id)
        {

            Compra Compra = Banco.Compras.Find(id);
            Banco.Compras.Remove(Compra);
            Banco.SaveChanges();

            return RedirectToAction("VerPacotesComprados");

        }
        public ActionResult Login()
        {

            return View(new Funcionario());

        }
        [HttpPost]
        public ActionResult Login(Funcionario f)
        {

            Funcionario fun = Banco.Funcionarios.FirstOrDefault(c => c.email == f.email && c.senha == f.senha);
            if (fun != null)
            {
                Session["Funcionario"] = fun;
                return RedirectToAction("Home");
            }
            if(f.email.ToLower() == "adm@adm" && f.senha == "adm")
            {
                return RedirectToAction("Home", "Adm");
            }
            return RedirectToAction("Login");

        }
        public ActionResult VerPacoteComprado(long id)
        {

            
            Funcionario f = Session["Funcionario"] as Funcionario;
            if (f != null)
            {
                ViewBag.Funcionario = f;
                Compra Compra = Banco.Compras.Find(id);

                VerPerfilView mc = new VerPerfilView();
                mc.Compra = Compra;
                mc.Sessao = Banco.Sessoes.Find(Compra.IdSessao);
                mc.Filme = Banco.Filmes.Find(mc.Sessao.IdFilme);
                mc.Pacote = Banco.Pacotes.Find(Compra.IdPacote);
                mc.Cliente = Banco.Clientes.Find(Compra.IdCliente);

                return View(mc);
            }
            return RedirectToAction("Login");

        }
        public ActionResult Editar(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f == null)
            {
                return RedirectToAction("Listar");
            }
            return View(f);
        }
        public ActionResult Excluir(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f != null)
            {
                Banco.Funcionarios.Remove(f);
                Banco.SaveChanges();
            }
            return RedirectToAction("Listar");
        }
        public ActionResult Ver(long? id)
        {

            Funcionario f = Banco.Funcionarios.Find(id);
            if (f != null)
            {
                return View(f);
            }
            return RedirectToAction("Listar");
        }
        [HttpPost]
        public ActionResult Editar(Funcionario f, HttpPostedFileBase arquivo)
        {
            if (ModelState.IsValid)
            {
                if (arquivo != null)
                {
                    f.TipoDaFoto = arquivo.ContentType;
                    f.Foto = SetLogoTipo(arquivo);

                }
                Banco.Entry(f).State = EntityState.Modified;
                Banco.SaveChanges();
                return RedirectToAction("Listar");
            }
            return RedirectToAction("Listar");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Funcionario f, HttpPostedFileBase arquivo)
        {

            if (arquivo != null)
            {
                f.TipoDaFoto = arquivo.ContentType;
                f.Foto = SetLogoTipo(arquivo);
            }
            Banco.Funcionarios.Add(f);
            Banco.SaveChanges();
            //return RedirectToAction("Visualizar", "Funcionarios");
            return RedirectToAction("Listar");

        }



        private byte[] SetLogoTipo(HttpPostedFileBase arquivo)
        {
            var bytesFile = new byte[arquivo.ContentLength];
            arquivo.InputStream.Read(bytesFile, 0, arquivo.ContentLength);
            return bytesFile;
        }
        public FileContentResult GetLogoTipo(int? id)
        {

            Funcionario F = Banco.Funcionarios.Find(id);
            if (F != null)
            {
                return File(F.Foto, F.TipoDaFoto);
            }
            return null;
        }

    }
}

source/AgendMovies/AgendMovies/Controllers/SessaoController.cs
using AgendMovies.Modelos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgendMovies.Controllers
{
    public class SessaoController : Controller
    {
        // GET: Sessao
      
        // GET: Sessions
        Tabelas Banco = new Tabelas();
        public ActionResult Cadastrar()
        {
            ICollection<Filme> fs = Banco.Filmes.OrderBy(f => f.FilmeId).ToList();
            List<SelectListItem> filmes = new List<SelectListItem>();
            foreach (Filme f in fs)
            {
                if (f.Categoria != "Em Breve")
                {
                    filmes.Add(new SelectListItem { Value = f.FilmeId, Text = f.Nome + "(" + f.FilmeId + ")" });
                }
               
            }

            ViewBag.Filmes = new SelectList(filmes, "Value", "Text");
            return View(new Sessao());
        }

        public ActionResult Listar()
        {
            List<string> Ids = new List<string>();
            foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.IdFilme).ToList())
            {
                if (Ids.IndexOf(s.IdFilme) == -1)
                {
                    Ids.Add(s.IdFilme);
                }
            }
            List<Filme> fs =new List<Filme>();
            foreach (Filme f in Banco.Filmes.OrderBy(se => se.FilmeId).ToList())
            {
                if (Ids.IndexOf(f.FilmeId) != -1)
                {
                    fs.Add(f);
                }
            }
            return View(fs);

        }

        public ActionResult VerSessoes(string Id, string dia)
        {

            Filme x = Banco.Filmes.Find(Id);
            if (x != null)
            {
                x.Sessoes = new List<Sessao>();

                if (dia == "seg" || dia == null)
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Monday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else if (dia == "ter")
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Tuesday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else if (dia == "qua")
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Wednesday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else if (dia == "qui")
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Thursday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else if (dia == "sex")
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Friday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else if (dia == "sab")
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Saturday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                else
                {
                    foreach (Sessao s in Banco.Sessoes.OrderBy(se => se.SessaoId).ToList())
                    {
                        if (s.IdFilme == x.FilmeId && s.data.DayOfWeek == DayOfWeek.Sunday)
                        {
                            x.Sessoes.Add(s);
                        }
                    }
                }
                ViewBag.Dia = dia;
                return View(x);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Editar(long id)
        {
                
            Sessao s = Banco.Sessoes.Find(id);
            if (s != null)
            {
                Filme f = Banco.Filmes.Find(s.IdFilme);
            s.NomeFilme = f.Nome;
                return View(s);
            }
                return RedirectToAction("VerSessoes", new { id = s.IdFilme, dia = "seg" });
        }
        [HttpPost]
        public ActionResult Editar(Sessao s)
            {

            Banco.Entry(s).State = EntityState.Modified;
            Banco.SaveChanges();
            return RedirectToAction("VerSessoes", new { id = s.IdFilme, dia = "seg" });
            }
        [HttpPost]
        public ActionResult Cadastrar(Sessao s, string quant, string dataf, string datai)
        {
            if (s.NomeFilme != "" || s.NomeFilme != null)
            {
               
            
            Filme f = Banco.Filmes.Find(s.NomeFilme);
            s.NomeFilme = f.Nome;
            s.IdFilme = f.FilmeId;

                string[] datasInicial = datai.Split('-');
            string[] datasFinal =dataf.Split('-');

            string diaInicialStr = datasInicial[2]+"/" + datasInicial[1]+ "/"+datasInicial[0];
            string diaFinalStr = datasFinal[2] + "/" + datasFinal[1] + "/" + datasFinal[0];
            string horaInicialStr = s.horaInicio;
            string duracaoMin = s.Duracao.ToString();
            string numSessoes = quant;
            DateTime diaInicial = DateTime.Parse(diaInicialStr);
            DateTime diaFinal = DateTime.Parse(diaFinalStr);
            DateTime dia = diaInicial;
            while (dia <= diaFinal)
            {
                TimeSpan horario = TimeSpan.Parse(horaInicialStr);
                TimeSpan duracao = new TimeSpan(0, int.Parse(duracaoMin), 0);
                for (int k = 0; k < int.Parse(numSessoes); k++)
                {
                    DateTime data = dia + horario;
                        
                    // Colocar o inserir no banco aqui!
                    Sessao se = new Sessao();
                    se.IdFilme = s.IdFilme;
                    se.data = data;
                    se.Sala = s.Sala;
                    se.horaInicio = horario.ToString(@"hh\:mm");
                    se.Duracao = duracaoMin;
                    se.NomeFilme = s.NomeFilme;
                    se.Idioma = s.Idioma;
                    Banco.Sessoes.Add(se);
                    Banco.SaveChanges();
                    horario = horario + duracao;


                }
                   
                dia = dia.AddDays(1);
            }
                
            }
            
        return RedirectToAction("Home", "Adm");

        }

        public ActionResult Excluir(long? id)
        {

            Sessao s = Banco.Sessoes.Find(id);

            if (s != null)
            {

                List<Compra> compras = Banco.Compras.OrderBy(c => c.IdSessao).Where(co => co.IdSessao == s.SessaoId).ToList();
                foreach (Compra c in compras)
                {
                    Banco.Compras.Remove(c);
                    Banco.SaveChanges();
                }
                Banco.Sessoes.Remove(s);
                Banco.SaveChanges();
                // Página de erro 404
            }
            return RedirectToAction("VerSessoes", new { id = s.IdFilme, dia = "seg" });


            // Redireciona para a página de listagem de filmes após a exclusão
        }


    }
}

source/AgendMovies/AgendMovies/Views/Employees/Cadastrar.cshtml
@model AgendMovies.Modelos.Funcionario

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-height, initial-scale=1.0">
    <title>Agend Movies</title>

    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link rel="icon" href="~/img/Logo_aba.png" />
    <link href="@Url.Content("~/styles/Cadastro_de_Funcionario.css")" rel="stylesheet" />

    @* Scriprs do barra automatico *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    @* Scriprs do barra automatico *@
    <style>
        input[type="file"] {
            display: none;
        }

        ion-icon:hover {
            cursor: pointer;
        }

        .wrapper form > div p span {
            color: #ff5454;
        }

        header {
            background-color: white;
        }
        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }
        body {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-content: space-between;
            min-height: 100vh;
        }

        header {
            position: relative !important;
            background-color: white;
        }

            header a {
                color: black !important;
            }

        footer {
            width: 100%;
        }

        #md {
            display: flex;
            align-items: center;
            gap: 1em;
        }

        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        header > div > p {
            color: black !important;
        }

    </style>
</head>
<body>

    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Adm")">Home</a></li>
            <li><a href="@Url.Action("Listar", "Filmes")">Filmes</a></li>
            <li><a href="@Url.Action("Listar", "Sessao")">Sessões</a></li>
            <li><a href="@Url.Action("Listar", "Employees")">Funcionários</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>

                    <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">



                </p>
            </a>
            <p id="per">Adm</p>
        </div>
    </header>

    <main>
        <div class="wrapper">
            @using (Html.BeginForm("Cadastrar", "Employees", FormMethod.Post,
 new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()



                <h1>Cadastro de Funcionários</h1>
                @Html.HiddenFor(model => model.FuncionarioId)

                <img onclick="EditarImagem()" src="~/img/iconeFuncionario.png" id="FotoTemp" style="width: 70px; height: 71px; border-radius:100%;" />
                @Html.TextBox("arquivo", "", new { type = "file", id = "ColocarFotoDePerfil" })
                <script>
                    function EditarImagem() {
                        var InputArquivo = document.getElementById("ColocarFotoDePerfil");
                        const Imagem = document.getElementById('FotoTemp');

                        InputArquivo.addEventListener("change", function (evento) {


                            const Arquivo = evento.target.files[0];
                            if (Arquivo) {
                                const LeitorDeArquivo = new FileReader();
                                LeitorDeArquivo.onload = function (e) {
                                    Imagem.setAttribute('src', e.target.result);
                                };
                                LeitorDeArquivo.readAsDataURL(Arquivo);
                            } else {
                                Imagem.setAttribute('src', '~/img/EditarPerfil.png');
                            }
                        });
                        InputArquivo.click();


                    }
                </script>

                <div><p>Nome Completo*   @Html.ValidationMessageFor(model => model.nome, "")</p>@Html.EditorFor(model => model.nome, new { type = "text", required = "required", size = "40" }) </div>

                <div><p>CPF*   @Html.ValidationMessageFor(model => model.cpf, "")</p>@Html.EditorFor(model => model.cpf, new { type = "text", required = "required", size = "40" }) </div>

                <div><p>Data de Nascimento*   @Html.ValidationMessageFor(model => model.data, "")</p>@Html.EditorFor(model => model.data, new { type = "text", required = "required", size = "40" }) </div>

                <div><p>Telefone*  @Html.ValidationMessageFor(model => model.telefone, "")</p>@Html.EditorFor(model => model.telefone, new { type = "text", required = "required", size = "40" }) </div>

                <div>
                    <p>Email*  @Html.ValidationMessageFor(model => model.email, "")</p> @Html.EditorFor(model => model.email, new { type = "email", required = "required", size = "40" })

                </div>


                <div>
                    <p>Senha*</p>
                    <input class="p" type="text" name="Nome" size="40" />

                </div>
                <div>
                    <p>Confirmar Senha*  @Html.ValidationMessageFor(model => model.senha, "")</p>
                    @Html.TextBoxFor(model => model.senha, new { type = "text", required = "required", size = "40" })
                </div>

                <div class="t">
                    <button type="submit" class="btn">Criar</button>
                </div>


            }
        </div>


        @* Scripts da validação *@
        <script src="@Url.Content("~/scripts/jquery-3.4.1.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.js")">
        </script>
        <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")">
        </script>
        @* Scripts da validação *@

        <script>
            $(document).ready(function () {
                $('#data').mask('00/00/0000');
            });
        </script>
    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>

</body>
</html>

source/AgendMovies/AgendMovies/Views/Employees/Editar.cshtml
@model AgendMovies.Modelos.Funcionario

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-height, initial-scale=1.0">
    <title>Agend Movies</title>

    <link rel="stylesheet" href="~/styles/DashboardPrincipal.css">
    <link rel="icon" href="~/img/Logo_aba.png" />
    <link href="@Url.Content("~/styles/Cadastro_de_Funcionario.css")" rel="stylesheet" />

    @* Scriprs do barra automatico *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    @* Scriprs do barra automatico *@
    <style>
        input[type="file"] {
            display: none;
        }

        ion-icon:hover {
            cursor: pointer;
        }

        .wrapper form > div p span {
            color: #ff5454;
        }

        header {
            background-color: white;
        }
        form {
            width: auto !important;
            height: auto !important;
            padding-bottom: 15px;
        }
            form input {
                border: none !important;
                box-sizing: border-box;
                outline: none;
                margin-left: 2px;
            }
        form > div {
            width: 100%;
            box-sizing: border-box;
            display: block;
        }
        form p {
            display: flex;
            align-items: center;
            align-content: center;
            box-sizing: border-box;
            border-bottom: 2px solid white;
            width: 100%;
     
            padding: 10px;
        }
        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }
        header {
            background-color: white;
        }

        .FotoPerfilHeader {
            width: 62px;
            height: 62px;
            border-radius: 100%;
        }

        body {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-content: space-between;
            min-height: 100vh;
        }

        header {
            position: relative !important;
            background-color: white;
        }

            header a {
                color: black !important;
            }

        footer {
            width: 100%;
        }

        #md {
            display: flex;
            align-items: center;
            gap: 1em;
        }


        header > div > p {
            color: black !important;
        }
    </style>
</head>
<body>

    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="~/img/logo.png">
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="@Url.Action("Home", "Adm")">Home</a></li>
            <li><a href="@Url.Action("Listar", "Filmes")">Filmes</a></li>
            <li><a href="@Url.Action("Listar", "Sessao")">Sessões</a></li>
            <li><a href="@Url.Action("Listar", "Employees")">Funcionários</a></li>
        </ul>
        <div id=md>
            <a href="#.html">
                <p>
                    <img class="FotoPerfilHeader" src="~/img/PerfilSemFoto.png">
                </p>
            </a>
            <p id="per">Adm</p>
        </div>
    </header>

    <main>
        <div class="wrapper">
            @using (Html.BeginForm("Editar", "Employees", FormMethod.Post,
 new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Foto)
                @Html.HiddenFor(model => model.TipoDaFoto)


                <h1>Edição de Funcionário</h1>
                @Html.HiddenFor(model => model.FuncionarioId)

                if (Model.Foto == null)
                {
                    <img onclick="EditarImagem()" src="~/img/iconeFuncionario.png" id="FotoTemp" style="width: 70px; height: 71px; border-radius:100%;" />
                }
                else
                {
                    <img onclick="EditarImagem()" src="@Url.Action("GetLogoTipo", "Employees", new {id = Model.FuncionarioId})" id="FotoTemp" style="width: 70px; height: 71px; border-radius:100%;">
                }

                @Html.TextBox("arquivo", "", new { type = "file", id = "ColocarFotoDePerfil" })
                <script>
                    function EditarImagem() {
                        var InputArquivo = document.getElementById("ColocarFotoDePerfil");
                        const Imagem = document.getElementById('FotoTemp');

                        InputArquivo.addEventListener("change", function (evento) {


                            const Arquivo = evento.target.files[0];
                            if (Arquivo) {
                                const LeitorDeArquivo = new FileReader();
                                LeitorDeArquivo.onload = function (e) {
                                    Imagem.setAttribute('src', e.target.result);
                                };
                                LeitorDeArquivo.readAsDataURL(Arquivo);
                            } else {
                                Imagem.setAttribute('src', '~/img/EditarPerfil.png');
                            }
                        });
                        InputArquivo.click();


                    }
                </script>

                <div>
                    <p>
                        Nome Completo:
                        @Html.EditorFor(model => model.nome, new { type = "text", required = "required", size = "40" })

                    </p>
                    @Html.ValidationMessageFor(model => model.nome, "")
                </div>

                <div>
                    <p>
                        CPF:
                        @Html.EditorFor(model => model.cpf, new { type = "text", required = "required", size = "40" })
                    </p>
                    @Html.ValidationMessageFor(model => model.cpf, "")
                </div>

                <div>
                    <p>
                        Data de Nascimento:
                        @Html.EditorFor(model => model.data, new { type = "text", required = "required", size = "40" })
                    </p>
                    @Html.ValidationMessageFor(model => model.data, "")
                </div>

                <div>
                    <p>Telefone:   @Html.EditorFor(model => model.telefone, new { type = "text", required = "required", size = "40" })</p>
                    @Html.ValidationMessageFor(model => model.telefone, "")

                </div>

                <div>
                    <p>Email: @Html.EditorFor(model => model.email, new { type = "email", required = "required", size = "40" })  </p>
                    @Html.ValidationMessageFor(model => model.email, "")
                </div>

                <div>
                    <p>Confirmar Senha*  @Html.TextBoxFor(model => model.senha, new { type = "text", required = "required", size = "40" }) </p>

                    @Html.ValidationMessageFor(model => model.senha, "")
                </div>

                <div class="t">
                    <button type="submit" class="btn">Atualizar</button>
                </div>


            }
        </div>


        @* Scripts da validação *@
        <script src="@Url.Content("~/scripts/jquery-3.4.1.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.js")">
        </script>
        <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")">
        </script>
        @* Scripts da validação *@

        <script>
            $(document).ready(function () {
                $('#data').mask('00/00/0000');
            });
        </script>
    </main>

    <footer>
        <div>
            <img src="~/img/footerMovieCat.png" style="width: 180px; height: 80px;">
        </div>
        <div>
            <img id="loucura" src="~/img/replitIcon.png">
            <img src="~/img/figmaIcon.png">
            <img src="~/img/githubIcon.png">
        </div>
    </footer>

</body>
</html>

source/AgendMovies/AgendMovies/Views/Employees/Login.cshtml
@model AgendMovies.Modelos.Funcionario

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/styles/LoginFunc.css">
    <title>HASH TECHIE OFFICIAL</title>
</head>
<body>
    <section>
        <div class="form-box">
            <div class="form-value">
                @using (Html.BeginForm("Login", "Employees", FormMethod.Post,
                        new { enctype = "multipart/form-data" }))

                {
                    <h2>Login</h2>
                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
       
                        @Html.TextBoxFor(model => model.email, new { type = "email", required = "required" })
                        <label for="">Email</label>
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        @Html.TextBoxFor(model => model.senha, new { type = "password", required = "required" })
          
                        <label for="">Senha</label>
                    </div>
                    <div class="forget">
                        <label for=""><input type="checkbox">Lembre de mim    <a href="#">Esqueci minha senha</a></label>

                    </div>
                    <button>Log in</button>
                    <div class="register">
                        <p> <a href="@Url.Action("Index", "Home")">Voltar</a></p>
                    </div>
                }
                </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>